### ISSUE TITLE
Unsupervised segmentation of real-world images

### ISSUE THREAD

**Issue by xlim1997** [MattWallingford/NeuralRadianceFieldCodebooks#2]
Hi,
Thanks for the excellent work. But I have a question about where you implement the code for Unsupervised segmentation of real-world images( Fig.3 in your paper.)？

**Comment by MattWallingford** [comment]
Hello, thanks for the interest in NRC. I haven't included the NYU eval in the current repository yet. At the moment the code supports training, PSNR evaluation, and visualization. I'm planning to release pretrained models and the eval for THOR/NYU depth in the next few weeks.
